[package]
name = "hello-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.4"

[[bench]]
name = "vector_bench"
harness = false

[[bench]]
name = "file_bench"
harness = false